git:
  depth: false
  quiet: true
language: java
jdk: openjdk8
env:
  global:
  - secure: f/ddrLmA5Vvp0WGRDuaCGDbhlCSMMZkQvoTfRs7CWJb2eI3Op6+lwUevV2e7hCorhtFW8XAm+OGF1GcD8wLgJuj8sYtgTzTjSfz9O6ToaV6Cq2E8zb046ScS0QWIc5TTHYYlCmR3F+iPKctWpN6QxUg+ichB0Z5Lcts/ffHYctoumG/7g8ZNjKQHswu2BEXRRylU6kYWX3OLe2H5reQB+UEGx2ViBWbuty7+rnwuWmkryZ3wzB1s0uMQsrQoxLNrTqwXVp/faCSd4hwoqaJdHyoJNt531pGVlL0Xq85x5XSOIpfbWYJuKsRY+2RFTdHQUoIkmebWw5epQsrR4PGdbfJ5Vreu0CRbIh4XRR4sVx6zuqaROO0WL0k4jTXE7pU/6iBuJzNCvnLBfCzhE3dArsLxRkUlsRx0WPuSiUhKHaXjWSdUS5D60iERHTkX6mY3cyeRxQP5eWb59Sya64xQrbU3IV29Xlx5DCIdYb20h4NmOBxV045t8hBl/Hw24Vv+6AilVOnRbIO8TqAXJVIDlGFCfUgSiE6AL3rOQ+Ais7OnT06CHp2D9FXiqSCa7iyP43wr/5d8m2973r3JWAJYC2QQgoz3GNXPLBltm676nQR0tBJKaR6uuMsPJ9IuYIF6nPIGCWdrkk2H7rkpO7y0GWBPthUMGTUoXUkuxATX1MM=
addons:
  apt:
    packages:
      - sudo
      - lsof
      - curl
      - bash
      - python-py
install: true
before_install:
  - sudo pip install --upgrade httpie >/dev/null
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80
script:
  - ./gradlew
  - bash ./build/libs/*.war &
  - wait_for 8080
  - http :8080/actuator/
  - http :8080/actuator/health
  - stop_any 80
cache:
  npm: true
  packages: true
  directories:
    - ./node_modules
    - ~/.gradle
notifications:
  email: false
before_deploy:
  - ./gradlew npm_run_build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
