version: '3.7'
services:
  app:
    image: openjdk:8u201-jre-alpine3.9
    volumes: ['./build/libs:/tmp/app']
    ports: ['8080:8080']
    networks: [app-network]
    command: ash -c 'java -jar /tmp/app/*.war'
    healthcheck:
      disable: true
networks:
  app-network:
    driver: bridge
